steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - kms
      - decrypt
      - --ciphertext-file=npmrc.enc
      - --plaintext-file=/root/.npmrc
      - --location=global
      - --keyring=my-keyring
      - --key=npm-key
    volumes:
      - name: "home"
        path: /root/
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
  - name: "node:22"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        apt-get update && apt-get install -y wget unzip
        wget -q "https://github.com/protocolbuffers/protobuf/releases/download/v23.1/protoc-23.1-linux-x86_64.zip"
        unzip -q protoc-23.1-linux-x86_64.zip -d /usr/local
        mkdir -p src/proto
        export PATH=/workspace/node_modules/.bin:$$PATH
        protoc --proto_path="./proto" --js_out="import_style=commonjs:src/proto" "./proto/emulator_controller.proto"
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
  - name: "gcr.io/cloud-builders/npm"
    args: ["test"]
  - name: "gcr.io/cloud-builders/npm"
    args: ["publish"]
    env:
      - HOME=/root/
    volumes:
      - name: "home"
        path: /root/
